### ISSUE TITLE
Can you teach me how to use it?

### ISSUE THREAD

**Issue by sylvoslee** [T4rk1n/pytest-dash#10]

**Comment by T4rk1n** [comment]
[pytest](https://docs.pytest.org/en/latest/) is pretty simple to use. It aims to modernize and simplify writing tests.

You write your test prefixed with `test_` and the argument are fixtures that you use in the test. The argument name will be used to identify the fixture. So if you want to use the selenium fixture in a test, you would write it like:

```python
def test_my_page(selenium):
    ...
```

To start a test run you run the command like:

`$ pytest tests/my_tests.py --driver Chrome`

You need to specify the selenium driver you use as the `--driver` argument. [Chromedriver](http://chromedriver.chromium.org/) needs to be on your PATH if using chrome.

You can use the `dash_threaded` fixtures of pytest-dash to start a dash app instance in a thread that will be closed when the test end. After calling the fixture to start the app, you can use selenium test the functionality of the app.

You can look at these examples:
https://github.com/T4rk1n/pytest-dash/blob/master/tests/test_integrations.py
https://github.com/plotly/dash-component-boilerplate/blob/64197cad90b5ef450715a2ff83247551ead337e6/%7B%7Bcookiecutter.project_shortname%7D%7D/tests/test_usage.py

I'll add proper documentation soon #9.

**Comment by T4rk1n** [comment]
Documentation now at https://pytest-dash.readthedocs.io/en/latest/usage.html#usage
