### ISSUE TITLE
Add usage examples.

### ISSUE THREAD

**Issue by T4rk1n** [T4rk1n/pytest-dash#21]
- [ ] dash_threaded examples.
- [ ] dash_subprocess example.
- [ ] dash_multiprocess example.

**Comment by berryt08** [comment]
It would be great if you could show the most basic of examples as to how to incorporate this module in conftest.py fixtures. Is it just like you would using flask and your plugin does the rest?

**Comment by T4rk1n** [comment]
@berryt08 There's a usage guide on the documentation homepage: https://pytest-dash.readthedocs.io/en/latest/usage.html

Just use `dash_threaded`/`dash_subprocess` to start a dash app and manipulate the page with the selenium driver on `dash_threaded.driver`. Start the tests `pytest tests/my_test.py --webdriver Chrome`.

You don't need to do anything in `conftest.py` unless you want to expand the behavior language with the `add_behavior` hook.

**Comment by berryt08** [comment]
@T4rk1n, thanks for this. Sorry, I have been on your docs page but was obviously blind not to see the Usage part.
